base_url: 'https://tauri.crowdin.com'
api_token_env: CROWDIN_TOKEN
project_id: 2
preserve_hierarchy: true
files:
  # Docs Markdown files
  - source: /src/content/docs/en/**/*
    translation: /src/content/docs/%locale%/**/%original_file_name%
